services:
  db:
    container_name: db
    hostname: db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: explicai
      TZ: GMT-3
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./ddl.sql:/docker-entrypoint-initdb.d/1.sql:ro

volumes:
  db-data:

networks:
  datanodes-network:
    driver: bridge